theme = "catppuccin_mocha"

[editor]
line-number = "relative"
mouse = true
middle-click-paste = true
rulers = [80]
shell = ["zsh", "-c"]
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.soft-wrap]
enable=true

[editor.file-picker]
hidden = false

# [editor.lsp]
# display-inlay-hints = true

[editor.statusline]
left = ["mode", "spinner", "file-modification-indicator", "file-name", "version-control"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"


[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-u = ["half_page_up", "align_view_center"]
C-d = ["half_page_down", "align_view_center"]